services:
  inn_app_mysql:
    image: 'mysql:latest'
    ports:
      - "3309:3309"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: inncontrol_backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10