services:
  - type: web
    name: inncontrol-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/inncontrol-backend-0.0.1-SNAPSHOT.jar
    environment:
      javaVersion: 17
